### PR TITLE
Explicitly load scribbler JS

### PR DESCRIPTION
**Pull request by vkurup**
@domdinicola this is what I was thinking might get things working again. Hard for me to tell without a deployed environment though...

### CODE REVIEW

**Comment by domdinicola** [comment]
it didn't help :(

**Comment by vkurup** [comment]
Hmm, I'm not seeing the scribbler.min.js line on https://rapidsms.unicef.io/ (or is it also deployed somewhere else?)

**Comment by domdinicola** [comment]
it has been deployed now

**Comment by vkurup** [comment]
Ahh, that must be a different issue then, but this fixes the scribbler issue.

**Pull request merged**
